### ISSUE TITLE
Add support for MoarSigns

### ISSUE THREAD

**Issue by brisingraerowing** [GirafiStudios/PassthroughSigns#1]
https://minecraft.curseforge.com/projects/moarsigns

**Comment by GirafiStudios** [comment]
Thanks for putting the suggestion on here :)
Currently working on a rewrite os Passthrough Signs so there will be an API that other mods can hook into and allow their signs (Or similiar) to be passhroughable.

**Comment by GirafiStudios** [comment]
Is now merged into Moar Signs with this commit https://github.com/GoryMoon/MoarSigns/commit/ceebb8ea5f428cea91c815e607803a26d070e118 , so closing this :)
