### ISSUE TITLE
[1.15] Holding shift when clicking sign with sign doesn't place it

### ISSUE THREAD

**Issue by NielsPilgaard** [GirafiStudios/PassthroughSigns#11]
When trying to place a sign against another sign by holding shift, nothing happens. 

- PassthroughSigns-1.15.2-2.3.3
- Quark-r2.1-245

**Comment by GirafiStudios** [comment]
Fix uploaded to CurseForge, just waiting for approval :)

**Comment by NielsPilgaard** [comment]
Damn that was fast, thanks!
