### ISSUE TITLE
[1.16.3] Right-clicking item frame is ignored when attached to non-interactable block

### ISSUE THREAD

**Issue by NielsPilgaard** [GirafiStudios/PassthroughSigns#12]
I have to hold shift to place something in item frames when they're attached to simple blocks like sand.

### Versions
- `PassthroughSigns-1.16.2-2.3.6`
- `Forge-1.16.3-34.1.42`

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/356

**Comment by GirafiStudios** [comment]
Thanks for the report!
New build with the fix will be available on CurseForge, once it's approved.

**Comment by NielsPilgaard** [comment]
Lovely, thanks :)
