### ISSUE TITLE
Crashes on 1.19 with new forge changes

### ISSUE THREAD

**Issue by wh0isit** [GirafiStudios/PassthroughSigns#14]
Works ok with forge 41.0.63.

[log](https://gist.githubusercontent.com/wh0isit/87d58bc0b6a45c52249130c151947943/raw/35777e85a11674c4ea0340dccb827d16cd1025f6/gistfile1.txt)

**Comment by GirafiStudios** [comment]
Unable to reproduce.
Didn´t notice this before now, sorry about that!
