### ISSUE TITLE
[1.19.2]Block will be placed when you right-click banner on the chest

### ISSUE THREAD

**Issue by ghost** [GirafiStudios/PassthroughSigns#16]
Block will be placed when you right-click flag on the chest

**Comment by ghost** [comment]
BTW,there is one another similar issue:If you have Quark installed and enable 'Shift-click to ignore signs' option,the block in hand will be placed when you shift-click the signs on the chest.

**Comment by GirafiStudios** [comment]
What exactly do you mean by "when you right-click flag"?
It´s the flag part, that I can´t get to make sense!

**Comment by ghost** [comment]
> 
Sry my expression may be not clear enough.
When you right-click a sign/painting/banner/item frame attached to a chest,you will open the chest.But if you right-click the banner/shift-click the sign attached the chest with placeable block in hand,this block will be placed.
Please watch this video

https://github.com/GirafiStudios/PassthroughSigns/assets/129179911/5021343d-b548-4394-9a0f-d0b552ba41ff

**Comment by GirafiStudios** [comment]
That´s intended behaviour :)

That´s the same as if you shift right-click a chest, then it will place the block you´re holding.

**Comment by ghost** [comment]
> That´s the same as if you shift right-click a chest, then it will place the block you´re holding.

The issue on banner don't need press shift to trigger.It can happen when you only right-click the banner.Is this also an intended behavior? It's enough to affect the gaming experience negatively,every time I open the chest,a block will be placed

**Comment by GirafiStudios** [comment]
Oh I see what you´re saying now!
No that´s indeed not intended.
