### ISSUE TITLE
[1.20.1 Forge] Clicks to passthrough do not register if player's blockreach is further than vanilla

### ISSUE THREAD

**Issue by Lucipo** [GirafiStudios/PassthroughSigns#17]
**Mod Version:** 1.20.1-2.6.3
**Loader:** Forge
**Happens on single/multiplayer?:** Yes

**Issue**: Further than vanilla blockreach will not let you open chests through signs/item frames
**To Reproduce:**

1) Get any item that extends your default block placing/destroy/interaction range (Aether's Valkyrie tools, Botania Ring of Far Reach)
2) Try to interact with a chest with a sign/item frame ontop from 3+ blocks away, you cannot open it.
You can click the sides of the chest to open them, but not any in which the Passthrough Mod comes into effect

**Comment by GirafiStudios** [comment]
Vanillas block reaching code is a huge mess. Got majorily change in 1.20.2 & will as well in 1.20.5 (It looks like).
I might look into fixing, if this is still an issue in the future, but I will unfortunately not fix it for 1.20.1

**Comment by Lucipo** [comment]
Thanks! Good thing it got more official support in the new versions, not sure if it's a smoother kind of spaghetti this time around though. Maybe they got kingbdogz to help, they nailed farther reach in 2011.
