### ISSUE TITLE
[1.21] Client crash java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState net.minecraft.world.level.Level.m_8055_(net.minecraft.core.BlockPos)'

### ISSUE THREAD

**Issue by ProsperCraft** [GirafiStudios/PassthroughSigns#19]
https://gist.github.com/ProsperCraft/ed8663292e85b85f94b2f90ec927778b

I loaded in to a new world on a multiplayer server, and within 30 seconds or so it crshed.

**Comment by GirafiStudios** [comment]
Only happens outside of dev for some reason.

The line it happens on is literally just a level.getBlockState. Potientially a bug in Forge?
https://github.com/GirafiStudios/PassthroughSigns/blob/master/forge/src/main/java/com/girafi/passthroughsigns/util/PassableHandler.java#L28

**Comment by GirafiStudios** [comment]
Dropping Forge support going forward
