### ISSUE TITLE
[1.12.2] Passthrough not working with Quark installed

### ISSUE THREAD

**Issue by matthijsvdmeulen** [GirafiStudios/PassthroughSigns#3]
I've got Quark r1.3-112 installed together with Passthrough Signs 2.1.3, and no matter what I disable in quark's configs, I can't get the passthrough effect to work.

How to reproduce:
Clean forge 14.23.0.2497
Quark r1.3-112
Passthrough Signs 2.1.3
all in Minecraft 1.12.2

**Comment by GirafiStudios** [comment]
Quark must have changed something recently. I will look into this as soon as possible!

**Comment by GirafiStudios** [comment]
Also have you tried holding shift while right clicking a sign?
Since that is required when Quark is installed, because of the sign editing feature.

**Comment by matthijsvdmeulen** [comment]
Well, my bad, that works. May I still suggest adding a config option to disable this behaviour when quark is installed, because I disabled signedit to allow the easy right clicking to happen, and did'nt realise that the behaviour was changing even if quark was installed but signedit not enabled
