### ISSUE TITLE
Support for client-side use on servers

### ISSUE THREAD

**Issue by IceController** [GirafiStudios/PassthroughSigns#4]
1.12.2 - Mod works in singleplayer, but doesn't in SMP. If this mod could be used client-side in a multiplayer server, that would be great. This is one of the greatest quality of life mod ideas I've come across.

**Comment by GirafiStudios** [comment]
Thanks for your report!
The mod needs to be installed on the server too. Unfortunately not possible to make it work, when just installed on the client.
