### ISSUE TITLE
When "Shift-click to ignore signs (Quark)" is false you should be able to ignore signs when not shifting

### ISSUE THREAD

**Issue by Insane96** [GirafiStudios/PassthroughSigns#5]
Right now if set to true (by default) shift-right-clicking a sign ignores the sign, while if not shifting the sign will be editable. When set to false now simply no longer able to interact with block behind. Instead it should be that with false would make the opposite, when shift-right-clicking you'll be able to edit the sign, instead when not will simply ignore the sign, interacting with the block behind.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
This is originally how I wanted the interaction with Quark to work, but it turned out not to be possible.
