### ISSUE TITLE
Port to 1.14.4

### ISSUE THREAD

**Issue by TheMysticalBard** [GirafiStudios/PassthroughSigns#7]
Could you please port the mod to 1.14.4 or update the files on CurseForge to include 1.14.4 as a version? It would greatly help modpack creators like myself to get onto more stable versions of Forge. Thank you!

**Comment by GirafiStudios** [comment]
It's currently not possible, since the Player Interaction event in Forge is not yet working for 1.14.4

**Comment by GirafiStudios** [comment]
I'll port it sometime before Friday.

**Comment by GirafiStudios** [comment]
The PlayerInteractionEvent is unfortunately still not fully working in Forge. It's only being called on client side, so I'll have to wait for Forge to fix this.
