### ISSUE TITLE
[1.14.4] Crash when right clicking an item frame

### ISSUE THREAD

**Issue by brisingraerowing** [GirafiStudios/PassthroughSigns#8]
[Crash Log](https://gist.github.com/BrisingrAerowing/458c5dbc5c458472c9bdd73cf7712de1)

Said item frame was attached to an oak planks block.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Do you mean a vanilla chest, or a oak chest from Quark?

**Comment by brisingraerowing** [comment]
Nope. A generic planks block.

**Comment by GirafiStudios** [comment]
Oh, interesting. Unfortunately I'm unable to reproduce the issue.
Could you try this build and see if it fixes it for you? https://jenkins.girafi.dk/job/Passthrough%20Signs/job/Passthrough%20Signs%201.14.4/7/

**Comment by brisingraerowing** [comment]
I’ll test when I get back to my computer later tonight (or possibly tomorrow if something comes up).

**Comment by brisingraerowing** [comment]
I just noticed the list of ASM transformers after each line, so I’ll test with those removed to see if one of them is breaking things.

**Comment by GirafiStudios** [comment]
It might be. Could you take a screenshot of the placement of the item frame that causes the crash?
I just noticed that it's actually crashing on a Stairs block, so maybe some mod that's making stairs into chairs.
I can probably fix it on my end, just need to be able to reproduce it first.

**Comment by brisingraerowing** [comment]
![2020-03-25_11 22 48](https://user-images.githubusercontent.com/250409/77553296-031d9000-6e8b-11ea-88a1-9b4d2f504c22.png)

I can't sit in stairs in this pack, so that's out of the question.

**Comment by brisingraerowing** [comment]
I just tried removing and replacing the item frame, and it crashed with the same error.

**Comment by brisingraerowing** [comment]
The testing version seems to fix the crash, and it still works as expected.

**Comment by GirafiStudios** [comment]
Glad to hear that the Jenkins build fixed the issue!
I'll release a new build on CurseForge in a bit.
